project:
  type: website
  output-dir: docs

website:
  title: "Project Repository"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
    right:
      - text: GitHub
        href: https://github.com/saonlib/project-search-website

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: false
    page-layout: full
